language: python
sudo: true
env:
  global:
    - PATH=$TRAVIS_BUILD_DIR/pandoc:$PATH
  matrix:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=pypy
    - TOXENV=flake8
install:
  - travis_retry pip install tox
before_script:
  - sudo add-apt-repository ppa:marutter/c2d4u -y
  - sudo apt-get update -q
  - sudo apt-get install pandoc pandoc-citeproc
script:
  - tox
